"""add rbac roles alerts video uploads password reset

Revision ID: dc14a9d062f3
Revises:
Create Date: 2026-09-06 20:34:17.482822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc14a9d062f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('video_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('stored_path', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('frame_count', sa.Integer(), nullable=True),
    sa.Column('persons_detected', sa.Integer(), nullable=False),
    sa.Column('fall_events_count', sa.Integer(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_uploads_id'), 'video_uploads', ['id'], unique=False)
    op.create_index(op.f('ix_video_uploads_user_id'), 'video_uploads', ['user_id'], unique=False)
    op.add_column('events', sa.Column('video_upload_id', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('recording_id', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('acknowledged', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('events', sa.Column('acknowledged_by', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('events', 'camera_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_events_recording_id'), 'events', ['recording_id'], unique=False)
    op.create_index(op.f('ix_events_video_upload_id'), 'events', ['video_upload_id'], unique=False)
    op.create_foreign_key(None, 'events', 'users', ['acknowledged_by'], ['id'])
    op.create_foreign_key(None, 'events', 'recordings', ['recording_id'], ['id'])
    op.create_foreign_key(None, 'events', 'video_uploads', ['video_upload_id'], ['id'])
    op.add_column('recordings', sa.Column('video_upload_id', sa.Integer(), nullable=True))
    op.alter_column('recordings', 'camera_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_recordings_video_upload_id'), 'recordings', ['video_upload_id'], unique=False)
    op.create_foreign_key(None, 'recordings', 'video_uploads', ['video_upload_id'], ['id'])
    op.add_column('users', sa.Column('role', sa.String(), server_default='viewer', nullable=False))
    # Data migration: preserve existing admin grants before the is_admin
    # column is dropped - anyone who was is_admin=true becomes role=admin,
    # everyone else keeps the 'viewer' default set above. (There is no
    # "operator" equivalent in the old schema, so nobody is auto-promoted
    # to operator; an admin can re-assign roles afterwards via
    # PUT /api/admin/users/{id}/role.)
    op.execute("UPDATE users SET role = 'admin' WHERE is_admin = true")
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False, server_default=sa.text('false')))
    op.execute("UPDATE users SET is_admin = true WHERE role = 'admin'")
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'recordings', type_='foreignkey')
    op.drop_index(op.f('ix_recordings_video_upload_id'), table_name='recordings')
    op.alter_column('recordings', 'camera_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('recordings', 'video_upload_id')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_index(op.f('ix_events_video_upload_id'), table_name='events')
    op.drop_index(op.f('ix_events_recording_id'), table_name='events')
    op.alter_column('events', 'camera_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('events', 'acknowledged_at')
    op.drop_column('events', 'acknowledged_by')
    op.drop_column('events', 'acknowledged')
    op.drop_column('events', 'recording_id')
    op.drop_column('events', 'video_upload_id')
    op.drop_index(op.f('ix_video_uploads_user_id'), table_name='video_uploads')
    op.drop_index(op.f('ix_video_uploads_id'), table_name='video_uploads')
    op.drop_table('video_uploads')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
